NCIEVS/report-exporter

- clientui/src/components/ReadCodeEntry.vue
- service/src/main/java/gov/nih/nci/evs/report/exporter/controller/CodeReadRestController.java
- service/src/main/java/gov/nih/nci/evs/report/exporter/controller/FileDownloadController.java
- service/src/main/java/gov/nih/nci/evs/report/exporter/controller/PropertyController.java
Feature/evsrepexp 15 - added cross origin for testing.
> Feature/evsrepexp 15 - added cross origin for testing.

- clientui/src/assets/app.scss
- clientui/src/components/ReadCodeEntry.vue
- clientui/src/components/ResolveBranchEntry.vue
EVSREPEXP-41 Added download format pulldown and verification.
> EVSREPEXP-41 Added download format pulldown and verification.

- clientui/src/api.js
- clientui/src/components/ResolveBranchEntry.vue
- service/src/main/java/gov/nih/nci/evs/report/exporter/controller/CuratedTopNodeController.java
EVSREPEXP-45 Added feature to select a curated top node or enter one and verify it.
> EVSREPEXP-45 Added feature to select a curated top node or enter one and verify it.

- clientui/src/components/ResolveBranchEntry.vue
Feature/evsrepexp 57 - added select to determine number of levels to retrieve
> Feature/evsrepexp 57 - added select to determine number of levels to retrieve

- clientui/src/components/ReadCodeEntry.vue
- clientui/src/components/ResolveBranchEntry.vue
Feature/evsrepexp 65 Converted read codes into a wizard.
> Feature/evsrepexp 65 Converted read codes into a wizard.

- clientui/src/App.vue
- clientui/src/components/FooterBar.vue
- clientui/src/components/HeaderBar.vue
- clientui/src/components/ReadCodeEntry.vue
- clientui/src/components/ReportSelection.vue
- clientui/src/components/ResolveBranchEntry.vue
- clientui/src/components/SubHeaderBar.vue
EVSREPEXP-69 Fixed header and footer. Updated text.
> EVSREPEXP-69 Fixed header and footer. Updated text.

- clientui/src/components/ReadCodeEntry.vue
- clientui/src/components/ResolveBranchEntry.vue
- service/src/main/resources/application.properties
Add validation for that export format is selected.
> EVSREPEXP-102 Add validation for that export format is selected.

- clientui/src/api.js
- clientui/src/components/ReadCodeEntry.vue
- clientui/src/components/ReportSelection.vue
- clientui/src/components/ResolveBranchEntry.vue
Feature/evsrepexp 108 - getting root nodes for tree.
> Feature/evsrepexp 108 - getting root nodes for tree.

- clientui/src/api.js
- clientui/src/components/ReadCodeEntry.vue
- clientui/src/components/ResolveBranchEntry.vue
- clientui/src/main.js
EVSREPEXP-112 created global var for baseURL and updated tree children REST call
> EVSREPEXP-112 created global var for baseURL and updated tree children REST call

- clientui/.env.development
- clientui/.env.production
- clientui/package.json
- clientui/src/api.js
- clientui/src/components/ErrorPage.vue
- clientui/src/components/ReadCodeEntry.vue
- clientui/src/components/ResolveBranchEntry.vue
- clientui/src/main.js
- clientui/vue.config.js
EVSREPEXP-124 Added .env.development and env.production files to determine dev/prod url for service.
> EVSREPEXP-124 Added .env.development and env.production files to determine dev/prod url for service.

- service/src/main/java/gov/nih/nci/evs/report/exporter/controller/FileDownloadController.java
- service/src/main/java/gov/nih/nci/evs/report/exporter/model/Format.java
> EVSREPEXP-67.  Creating a service that includes both the Format tag and it's description.

- clientui/src/components/ReadCodeEntry.vue
- clientui/src/components/ResolveBranchEntry.vue
EVSREPEXP-133 Added download format descriptions.
> EVSREPEXP-133 Added download format descriptions.

- clientui/pom.xml
…URL values for server and client
> EVSREPEXP-132.  Adding ability to build according to tier which setsURL values for server and client

- clientui/.env.development
- clientui/.env.local
- clientui/.env.qa
- clientui/.env.stage
- clientui/package.json
EVSREPEXP-139 - added NPM build scripts for local, dev, qa, stage, prod
> EVSREPEXP-139 - added NPM build scripts for local, dev, qa, stage, prod

- clientui/src/assets/app.scss
- clientui/src/assets/documentation.scss
- clientui/src/components/Documentation.vue
- clientui/src/components/HeaderBar.vue
- clientui/src/components/SubHeaderBar.vue
- clientui/src/main.js
EVSREPEXP-141 Add a Documentation page with FAQs
> EVSREPEXP-141 Add a Documentation page with FAQs

- clientui/src/components/ResolveBranchEntry.vue
EVSREPEXP-165 - Updated the levels parameter to match the API.
> EVSREPEXP-165 - Updated the levels parameter to match the API.

- clientui/src/components/ReadCodeEntry.vue
- clientui/src/components/SubHeaderBar.vue
EVSREPEXP-167 validating list of concept codes.  make sure there isn't 2 commas with no code in between.
> EVSREPEXP-167 validating list of concept codes.  make sure there isn't 2 commas with no code in between.

- clientui/src/components/Documentation.vue
- clientui/src/components/ReadCodeEntry.vue
- clientui/src/components/ReportSelection.vue
- clientui/src/components/ResolveBranchEntry.vue
EVSREPEXP-176 Scroll to top of page when you first go to it.
> EVSREPEXP-176 Scroll to top of page when you first go to it.

- service/src/main/java/gov/nih/nci/evs/report/exporter/service/BranchResolutionService.java
- service/src/main/java/gov/nih/nci/evs/report/exporter/service/CodeReadService.java
- service/src/main/java/gov/nih/nci/evs/report/exporter/service/EVSAPIBaseService.java
- service/src/main/java/gov/nih/nci/evs/report/exporter/service/FormattedOutputService.java
- service/src/main/java/gov/nih/nci/evs/report/exporter/service/RestRootNodeService.java
- service/src/main/java/gov/nih/nci/evs/report/exporter/service/TerminologyPropertyService.java
- service/src/test/java/gov/nih/nci/evs/report/exporter/serivce/BranchResolutionServiceTest.java
- service/src/test/java/gov/nih/nci/evs/report/exporter/serivce/CodeReadUtilityMethodsTest.java
- service/src/test/java/gov/nih/nci/evs/report/exporter/serivce/TerminologyPropertyServiceTest.java
Also consolidates the interface with the EVS API in one class
> EVSREPEXP-168. Refactoring and redoing tests to accomodate use of the WebClient.

- clientui/src/components/ResolveBranchEntry.vue
LEXEVS-4982 - Added error message for branch resolve page when network is down.
> LEXEVS-4982 - Added error message for branch resolve page when network is down.

- clientui/package.json
- clientui/src/components/NCIWarning.vue
- clientui/src/components/ReportSelection.vue
- clientui/src/components/ResolveBranchEntry.vue
- clientui/src/main.js
EVSREPEXP-245 Added warning NCI dialog. Added cookie to only show only once per day
> EVSREPEXP-245 Added warning NCI dialog. Added cookie to only show only once per day

- clientui/src/components/ReadCodeEntry.vue
- clientui/src/components/ResolveBranchEntry.vue
EVSREPEXP-229 Updated error message for invalid code entered.
> EVSREPEXP-229 Updated error message for invalid code entered.

- clientui/src/api.js
- service/src/main/java/gov/nih/nci/evs/report/exporter/service/CodeReadService.java
- service/src/main/java/gov/nih/nci/evs/report/exporter/service/EVSAPIBaseService.java
Bugfix/evsrepexp 230 - Endoding concept codes
> Bugfix/evsrepexp 230 - Endoding concept codes

- clientui/src/components/Downloads.vue
- clientui/src/components/ResolveBranchEntry.vue
- service/src/main/java/gov/nih/nci/evs/report/exporter/controller/FileDownloadController.java
- service/src/main/java/gov/nih/nci/evs/report/exporter/model/DeferredStatus.java
- service/src/main/java/gov/nih/nci/evs/report/exporter/service/TimedDeferredResultWrapper.java
- service/src/main/java/gov/nih/nci/evs/report/exporter/util/CommonServices.java
Feature/evsrepexp 265 Added ability to search for download Id
> Feature/evsrepexp 265 Added ability to search for download Id

- clientui/package.json
EVSREPEXP-285 Updated Axios version to 0.21.1
> EVSREPEXP-285 Updated Axios version to 0.21.1

- clientui/src/components/Documentation.vue
EVSREPEXP-284 Added documentation for deferred downloads.
> EVSREPEXP-284 Added documentation for deferred downloads.

- clientui/.env.production
- clientui/.env.stage
EVSREPEXP-293 Updated service URL for different stages.
> EVSREPEXP-293 Updated service URL for different stages.

- clientui/src/components/NCIWarning.vue
- clientui/src/components/ResolveBranchEntry.vue
Feature/evsrepexp 295 Added download link and scrollbar to the NCI warning dialog
> Feature/evsrepexp 295 Added download link and scrollbar to the NCI warning dialog

- clientui/package.json
- clientui/src/App.vue
- clientui/src/main.js
EVSREPEXP-207 add Security headers and attributes.
> EVSREPEXP-207 add Security headers and attributes.

- service/pom.xml
> EVSREPEXP-316. Updating jackson data bind

- clientui/package.json
EVSREPEXP-355 Updated jquery version to 3.6.0
> EVSREPEXP-355 Updated jquery version to 3.6.0

- clientui/src/components/Roles.vue
EVSREPEXP-363 - added CSS for spacing the badge for concepts.
> EVSREPEXP-363 - added CSS for spacing the badge for concepts.

- clientui/src/components/EntitySelection.vue
- clientui/src/components/ExportFormat.vue
- clientui/src/components/ReadCodeEntry.vue
- clientui/src/components/ResolveBranchEntry.vue
- clientui/src/components/Roles.vue
Featurey/evsrepexp 370 Created UI plugins for entity selection and export format
> Featurey/evsrepexp 370 Created UI plugins for entity selection and export format

- clientui/src/api.js
- clientui/src/components/Associations.vue
- clientui/src/components/EntitySelection.vue
- clientui/src/components/ReportSelection.vue
- clientui/src/main.js
EVSREPEXP-380 - add association feature to the UI
> EVSREPEXP-380 - add association feature to the UI

- clientui/src/components/Associations.vue
- clientui/src/components/Documentation.vue
- clientui/src/components/ReportSelection.vue
- clientui/src/components/Roles.vue
Feature/evsrepexp 388 Update documentation, file download names and report selection text
> Feature/evsrepexp 388 Update documentation, file download names and report selection text

- clientui/.env.development
- clientui/.env.production
- clientui/.env.qa
- clientui/.env.stage
- clientui/vue.config.js
EVSREPEXP-390 Updated UI config files for new domain.
> EVSREPEXP-390 Updated UI config files for new domain.

- clientui/src/components/Documentation.vue
- clientui/src/components/EntitySelection.vue
Feature/evsrepexp 395 Updated warning dialog for roles and associations.
> Feature/evsrepexp 395 Updated warning dialog for roles and associations.

- clientui/.env.development
- clientui/.env.production
Feature/evsrepexp 399 Updated dev and prod google analytic ids for new domain
> Feature/evsrepexp 399 Updated dev and prod google analytic ids for new domain

- clientui/package-lock.json
EVSREPEXP-414 NPM package updates
> EVSREPEXP-414 NPM package updates

- clientui/src/components/FooterBar.vue
EVSREPEXP-415 removed footer link for "Viewing File"
> EVSREPEXP-415 removed footer link for "Viewing File"

- clientui/src/components/Exports.vue
EVSREPEXP-421 Fixed spelling error.
> EVSREPEXP-421 Fixed spelling error.

- clientui/package-lock.json
- clientui/package.json
EVSREPEXP-422 Remove node-sass (replace with dart sass)
> EVSREPEXP-422 Remove node-sass (replace with dart sass)

- clientui/package-lock.json
- clientui/package.json
Bugfix/evsrepexp 422 updated version of node-sass
> Bugfix/evsrepexp 422 updated version of node-sass

- service/src/main/resources/application.properties
Don't allow stacktrace to appear in response
> Remove StackTrace

- clientui/package-lock.json
Updated prismjs package to 1.27.0
> EVSREPEXP-443 Fix vulnerability for prismjs component

- .idea/inspectionProfiles/Project_Default.xml
- clientui/package-lock.json
EVSREPEXP-460 Whitelabel error
>  EVSREPEXP-460 Whitelabel error

- service/src/main/resources/application.properties
- service/src/main/resources/templates/error.html
EVSREPEXP-460 Whitelabel error
> EVSREPEXP-460 Whitelabel error

- clientui/src/components/ResolveBranchEntry.vue
> EVSREPEXP-486

- clientui/src/components/ReadCodeEntry.vue
> EVSREPEXP-493 Apply Templating
